version: "2"
services:
  web:
    build: .
    command: npm start
    links:
      - mongodb
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - .:/var/www/shared/dockerdata
